README.md
Updated the link of the project board.
=> 📝 Fixed link to project board

apps/pawdopt/src/app/home/home.page.html
Home page will act as the tinder home, the creation of login/signup is needed as well.
=> Created basic layout page at home

apps/pawdopt/src/app/home/home.module.ts, apps/pawdopt/src/app/home/home.page.html, apps/pawdopt/src/app/home/home.page.scss, apps/pawdopt/src/app/home/home.page.ts, apps/pawdopt/src/main.ts
Needs to be converted to a lib once done.
=> Added basic outline for tinder swiping

apps/pawdopt/src/app/home/home.page.html, apps/pawdopt/src/app/home/home.page.ts
Changed from chatbubbles to a user button within the top nav bar.
=> Changed layout to match mockup better.

apps/pawdopt/src/app/home/home.page.html, apps/pawdopt/src/app/home/home.page.ts
Provided the like and dislike buttons.
=> Added button functionality to swipe.

apps/pawdopt/src/app/app-routing.module.ts, apps/pawdopt/src/app/home/home.module.ts, apps/pawdopt/src/main.ts, apps/pawdopt/src/theme/variables.scss, libs/mobile/adddog/feature/.babelrc, libs/mobile/adddog/feature/.eslintrc.json, libs/mobile/adddog/feature/README.md, libs/mobile/adddog/feature/jest.config.js, libs/mobile/adddog/feature/project.json, libs/mobile/adddog/feature/src/index.ts, libs/mobile/adddog/feature/src/lib/adddog-routing.module.ts, libs/mobile/adddog/feature/src/lib/adddog.module.ts, libs/mobile/adddog/feature/src/lib/adddog.page.html, libs/mobile/adddog/feature/src/lib/adddog.page.scss, libs/mobile/adddog/feature/src/lib/adddog.page.ts, libs/mobile/adddog/feature/tsconfig.json, libs/mobile/adddog/feature/tsconfig.lib.json, libs/mobile/adddog/feature/tsconfig.spec.json, tsconfig.base.json, workspace.json
- Removed unused imports
- Added dog page
- Changed tertiary colour in variables.scss to #2a0800
- Changed tertiary colour rgb in variables.scss to 0,0,0
=> 🚀 🔥 ✨ 💄 (UI): Added add dog page

apps/pawdopt/src/app/app-routing.module.ts, libs/mobile/uikit/feature/.babelrc, libs/mobile/uikit/feature/.eslintrc.json, libs/mobile/uikit/feature/README.md, libs/mobile/uikit/feature/jest.config.js, libs/mobile/uikit/feature/project.json, libs/mobile/uikit/feature/src/index.ts, libs/mobile/uikit/feature/src/lib/uikit-routing.module.ts, libs/mobile/uikit/feature/src/lib/uikit.module.ts, libs/mobile/uikit/feature/src/lib/uikit.page.html, libs/mobile/uikit/feature/src/lib/uikit.page.scss, libs/mobile/uikit/feature/src/lib/uikit.page.ts, libs/mobile/uikit/feature/tsconfig.json, libs/mobile/uikit/feature/tsconfig.lib.json, libs/mobile/uikit/feature/tsconfig.spec.json, tsconfig.base.json, workspace.json
Added the UI-Kit page with routing to main home page.
=> Added provision including the routing and page for the UI-Kit

libs/mobile/uikit/feature/src/lib/uikit.page.html, libs/mobile/uikit/feature/src/lib/uikit.page.scss
Feel free to change or add as you wish.
=> Created basis UI-Kit with all universal components.

.github/workflows/index.yml, .github/workflows/nxtest.yml
=> ✨ (CI): Added workflows test

.github/workflows/nxtest.yml
=> 🔥 (CI): Removed codecov

.github/workflows/full.yml
Testing the workflow test in a pr
=> ✅ (CI): Test worklfow

Test.txt
Added full.yml to test the workflow on a pr.
=> ✅ (CI): Testing workflow

.github/workflows/nxtest.yml, Test.txt
Updated the codecov token to work on a test
=> ✅ (CI): Added codecov secret token

package.json
Updated the dependencies for  nrwl/nest
=> 🐛 (CI): Typo in the dependencies

yarn.lock
=> 🐛(CI): Updated  lock file

yarn.lock
=> 🔥 (CI): Updated lock

package.json, yarn.lock
=> ✨ (CI): Updated Typescript

libs/backend/shell/api/feature/src/lib/api.schema.ts
Classes created:
- Dog
- User
1. Adopter
2. OrgMember
- Organisation
- ContactInfo
- Location
- Doc
- Image
=> 🚀 🚧 DB: Created classes

libs/backend/shell/api/feature/src/lib/api.dto.ts, libs/backend/shell/api/feature/src/lib/api.resolver.ts, libs/backend/shell/api/feature/src/lib/api.schema.ts, libs/backend/shell/api/feature/src/lib/api.service.ts, libs/backend/shell/api/feature/src/lib/backend-shell-api-feature.module.ts, schema.gql
Co-authored-by: Aramnand <Aramnand@users.noreply.github.com>
Co-authored-by: Chris Magerat <ChrisMagerat@users.noreply.github.com>
Co-authored-by: Rayden Logan Burger <rayden96@users.noreply.github.com>
Co-authored-by: Kearon Foba <KearonF@users.noreply.github.com>
=> 🐛 (API): Fixed API issues

libs/backend/shell/api/feature/src/lib/api.dto.ts, libs/backend/shell/api/feature/src/lib/api.resolver.ts, libs/backend/shell/api/feature/src/lib/api.schema.ts, libs/backend/shell/api/feature/src/lib/api.service.spec.ts, libs/backend/shell/api/feature/src/lib/api.service.ts, libs/backend/shell/api/feature/src/lib/backend-shell-api-feature.module.ts, schema.gql, yarn.lock
Co-authored-by: Rayden Logan Burger <rayden96@users.noreply.github.com>
Co-authored-by: Kearon Foba <KearonF@users.noreply.github.com>
Co-authored-by: Aramnand <Aramnand@users.noreply.github.com>
=> 🚑 Updates to schema and API

libs/backend/shell/api/feature/src/lib/api.resolver.ts, libs/backend/shell/api/feature/src/lib/api.service.ts, libs/mobile/addorg/feature/src/lib/addorg.page.html, libs/mobile/addorg/feature/src/lib/addorg.page.ts, libs/mobile/signup/feature/src/lib/signup.page.ts, libs/mobile/userinfo/feature/src/lib/userinfo.page.ts
Integrated addorg
Modified signup
=> ✨ 🔥 (API): Integrated addorg

libs/backend/shell/api/feature/src/lib/api.dto.ts, libs/backend/shell/api/feature/src/lib/api.resolver.ts, libs/backend/shell/api/feature/src/lib/api.schema.ts, libs/backend/shell/api/feature/src/lib/api.service.spec.ts, libs/backend/shell/api/feature/src/lib/api.service.ts, libs/backend/shell/api/feature/src/lib/backend-shell-api-feature.module.ts
Added unit tests for all of the queries
=> ✅  (API+DB): Added unit testing for API and DB queries

libs/mobile/login/feature/src/lib/login.page.html, libs/mobile/owneddogs/feature/src/lib/owneddogs.page.html, libs/mobile/owneddogs/feature/src/lib/owneddogs.page.scss, libs/mobile/owneddogs/feature/src/lib/owneddogs.page.ts, libs/mobile/userinfo/feature/src/lib/userinfo.page.html, libs/mobile/userinfo/feature/src/lib/userinfo.page.ts, libs/mobile/userprofile/feature/src/lib/userprofile.page.html
Owned dogs page
Login page
User info/profile page
=> Completed UI Fixes 💄 

libs/mobile/login/feature/src/lib/login.module.ts, libs/mobile/login/feature/src/lib/login.page.ts, libs/mobile/owneddogs/feature/src/lib/owneddogs.page.ts
When using VarsFacade, add it into the providers for that component
=> (State management) 🚑  : Fixed null injector issue with state management

libs/backend/shell/api/feature/src/lib/api.dto.ts, libs/backend/shell/api/feature/src/lib/api.resolver.ts, libs/backend/shell/api/feature/src/lib/api.schema.ts, libs/backend/shell/api/feature/src/lib/api.service.ts, libs/mobile/adddog/feature/src/lib/adddog.page.ts, libs/mobile/dashboard/feature/src/lib/dashboard.module.ts, libs/mobile/dashboard/feature/src/lib/dashboard.page.ts, schema.gql
=> Fixed ID issue with dogs ⛷️ 

libs/backend/shell/api/feature/src/lib/api.dto.ts, libs/backend/shell/api/feature/src/lib/api.resolver.ts, libs/backend/shell/api/feature/src/lib/api.schema.ts, libs/mobile/addorg/feature/src/lib/addorg.page.html, libs/mobile/addorg/feature/src/lib/addorg.page.scss, libs/mobile/addorg/feature/src/lib/addorg.page.ts, libs/mobile/login/feature/src/lib/login.page.ts, libs/mobile/signup/feature/src/lib/signup.page.ts, schema.gql
- Made addorg also add orgmembers
- Updated adopter and orgmember to have _id instead of uid
=> (UI, API)💄 🚀 : updated addorg, login and signup

libs/backend/shell/api/feature/src/lib/api.dto.ts, libs/backend/shell/api/feature/src/lib/api.resolver.ts, libs/backend/shell/api/feature/src/lib/api.schema.ts, libs/backend/shell/api/feature/src/lib/api.service.ts, libs/mobile/adddog/feature/src/lib/adddog.page.ts, libs/mobile/addorg/feature/src/lib/addorg.page.scss, libs/mobile/addorg/feature/src/lib/addorg.page.ts, libs/mobile/adoptionprocess/feature/src/lib/adoptionprocess.page.ts, libs/mobile/login/feature/src/lib/login.page.html, libs/mobile/login/feature/src/lib/login.page.ts, libs/mobile/orgprofile/feature/src/lib/orgprofile.page.ts, libs/mobile/owneddogs/feature/src/lib/owneddogs.page.html, libs/mobile/owneddogs/feature/src/lib/owneddogs.page.ts, libs/mobile/signup/feature/src/lib/signup.page.ts, libs/mobile/userlikes/feature/src/lib/userlikes.page.html, libs/mobile/userlikes/feature/src/lib/userlikes.page.ts, libs/shared/data-store/src/lib/vars-store/state/vars.actions.ts, libs/shared/data-store/src/lib/vars-store/state/vars.facade.ts, libs/shared/data-store/src/lib/vars-store/state/vars.reducer.ts, libs/shared/data-store/src/lib/vars-store/state/vars.selectors.ts, schema.gql
Made a lot of changes to the state management stuff and the api.
=> (Multiple areas)🚧 💄 🚀 ⚡️ 🎨 : Major changes

apps/pawdopt/src/app/app-routing.module.ts, apps/pawdopt/src/app/home/home.page.ts, libs/backend/shell/api/feature/src/lib/api.service.ts, libs/mobile/addorg/feature/src/lib/addorg.page.ts, libs/mobile/orgsettings/feature/.babelrc, libs/mobile/orgsettings/feature/.eslintrc.json, libs/mobile/orgsettings/feature/README.md, libs/mobile/orgsettings/feature/jest.config.ts, libs/mobile/orgsettings/feature/project.json, libs/mobile/orgsettings/feature/src/index.ts, libs/mobile/orgsettings/feature/src/lib/orgsettings-routing.module.ts, libs/mobile/orgsettings/feature/src/lib/orgsettings.module.ts, libs/mobile/orgsettings/feature/src/lib/orgsettings.page.html, libs/mobile/orgsettings/feature/src/lib/orgsettings.page.scss, libs/mobile/orgsettings/feature/src/lib/orgsettings.page.ts, libs/mobile/orgsettings/feature/tsconfig.json, libs/mobile/orgsettings/feature/tsconfig.lib.json, libs/mobile/orgsettings/feature/tsconfig.spec.json, libs/mobile/owneddogs/feature/src/lib/owneddogs.page.ts, libs/mobile/preferences/feature/src/lib/preferences.page.html, libs/mobile/preferences/feature/src/lib/preferences.page.ts, libs/mobile/userinfo/feature/src/lib/userinfo.page.html, libs/mobile/userinfo/feature/src/lib/userinfo.page.scss, libs/mobile/userinfo/feature/src/lib/userinfo.page.ts, libs/mobile/userprofile/feature/src/lib/userprofile.page.html, libs/mobile/userprofile/feature/src/lib/userprofile.page.ts, tsconfig.base.json, workspace.json
Co-authored-by: Kearon Foba <KearonF@users.noreply.github.com>
Co-authored-by: Aramnand <Aramnand@users.noreply.github.com>
Co-authored-by: Rayden Logan Burger <rayden96@users.noreply.github.com>
Co-authored-by: Alex Küsel <u19236183@tuks.co.za>
=> 🚀 preferences+userprofile+userinfo
